### ISSUE TITLE
重新编译 'IOKit/hid/IOHIDEvent.h' file not found

### ISSUE THREAD

**Issue by sundaoran** [iolate/SimulateTouch#23]
从cydia 下载的库不包含 button方法  重新编译就报 'IOKit/hid/IOHIDEvent.h' file not found，请问这是哪里出错啦，加载iokit 后 报错 'libkern/OSTypes.h' file not found

**Comment by sundaoran** [comment]
加在iokit后有报 'libkern/OSTypes.h' file not found

**Comment by cybmp3** [comment]
从cydia 下载的库不包含 button方法 重新编译就报 'IOKit/hid/IOHIDEvent.h' file not found，请问这是哪里出错啦，加载iokit 后 报错 'libkern/OSTypes.h' file not found
The library download from cydia not contain the method of button. It appears
" 'IOKit/hid/IOHIDEvent.h'  file not found " when I rebuild .And it appears “'libkern/OSTypes.h' file not found” after loaded iokit.
I wonder where is wrong?
Thanks!

**Comment by sundaoran** [comment]
I'm sorry, didn't use English to ask questions.Now the question is  ST Error: MessagePort is invalid

**Comment by yuzhouheike** [comment]
怎么解决的啊
